<!DOCTYPE html>
<html class="no-js h-100" lang="es">

<head>
    <?php extend_view(['admin/common/head'], $data) ?>
    <?php load_style(['bootstrap', 'jquery-ui', 'admin/style', 'admin/shards-dashboards.1.1.0.min']); ?>
    <?php load_style_plugin(['toast/toastr.min', 'select2/select2', 'select2/select2-bootstrap', 'bootstrap-table/bootstrap-table']); ?>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body data-ntipoempleadosupervisor="<?= $nIdRolSupervisor ?>" data-ntipoempleadoasesorventas="<?= $nIdRolAsesorVentas ?>" data-nidnegocio="<?= $nIdNegocio ?>" data-nidetapacierre="<?= $nIdEtapaCierre ?>" data-nrol="<?= $user["nIdRol"] ?>" data-nidsupervisor="<?= $nIdSupervisor ?>" data-nidentidadvendedor="<?= $nIdEntidadVendedor ?>">

    <div class="page-loader">
        <div class="loader-dual-ring"></div>
    </div>

    <div class="container-fluid">

        <div class="row">

            <?php extend_view(['admin/common/aside'], $data) ?>

            <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">

                <?php extend_view(['admin/common/navbar'], $data) ?>

                <div class="main-content-container container-fluid px-2 my-2"">


                    <div class=" container-fluid px-0">
                    <div class="page-header row no-gutters py-0">
                        <div class="col-lg-12 col-md-12 col-sm-12 mb-4">
                            <div class="card card-small">
                                <div class="card-body pt-1 pb-5">


                                    <div class="row">

                                        <div class="col-12">
                                            <div class="d-flex align-items-center bd-highlight">
                                                <div class="flex-grow-1 bd-highlight">
                                                    <h6 id="sTituloEmpleado" class="m-0">Vendedores registrados :</h6>
                                                </div>
                                                <div class="bd-highlight">
                                                    <button type="button" id="btnCrearEmpleado" class="btn btn-gradient-primary btn-rounded btn-icon">
                                                        <i class="fas fa-plus-circle"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>

                                    </div>

                                    <div id="toolbarBDEmpleados">
                                        <button id="btnFilter" class="btn btn-gradient-primary-table mx-1" type="button" title="Filtros">
                                            <i class="fas fa-filter"></i>
                                        </button>
                                    </div>

                                    <div class="table-responsive">

                                        <table data-toggle="table" id="tblBDEmpleados" data-card-view="false" data-toggle="table" data-search="true" data-query-params="queryParams" toolbarAlign="left" data-show-refresh="false" data-pagination="true" data-toolbar="#toolbarBDEmpleados" data-buttons-align="left" data-show-columns="true" data-pagination-h-align="left" data-pagination-detail-h-align="right" data-classes="table table-hover table-condensed" data-striped="true" data-buttons-class="gradient-primary-table" data-card-view="false" data-page-size="14" data-sort-name="" data-sort-order="asc">
                                            <thead>

                                            </thead>
                                            <tbody>

                                            </tbody>
                                        </table>

                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>


        </div>

        </main>
    </div>
    </div>

 
</body>



<?php extend_view(['admin/common/scripts'], $data) ?>

<?php load_script(['jquery', 'jquery-ui', 'popper', 'bootstrap', 'moment', 'admin/custom', 'admin/functions', 'admin/edit-user-empleado', 'admin/app']); ?>
<?php load_script_plugin([
    'toast/toastr.min',
    'select2/select2',

    'bootstrap-table/bootstrap-table',
    'bootstrap-table/bootstrap-table-es-ES',

    'bootstrap-table/export/tableExport/tableExport',
    'bootstrap-table/export/tableExport/html2canvas',
    'bootstrap-table/export/tableExport/jquery.base64',
    'bootstrap-table/export/tableExport/tableExport',
    'bootstrap-table/export/bootstrap-table-export',


    'bootstrap-table/mobile/bootstrap-table-mobile',
    'bootstrap-table/tableExport/libs/FileSaver/FileSaver.min',
    'bootstrap-table/tableExport/libs/js-xlsx/xlsx.core.min',
    'bootstrap-table/tableExport/libs/jsPDF/jspdf.min',
    'bootstrap-table/tableExport/libs/jsPDF-AutoTable/jspdf.plugin.autotable',
    'bootstrap-table/tableExport/libs/pdfmake/pdfmake.min',
    'bootstrap-table/tableExport/libs/pdfmake/vfs_fonts',
    'bootstrap-table/tableExport/tableExport.min',
]); ?>

<?php

load_script_plugin([
    'bootstrap-table/mobile/bootstrap-table-mobile',
    'bootstrap-table/tableExport/libs/FileSaver/FileSaver.min',
    'bootstrap-table/tableExport/libs/js-xlsx/xlsx.core.min',
    'bootstrap-table/tableExport/libs/jsPDF/jspdf.min',
    'bootstrap-table/tableExport/libs/jsPDF-AutoTable/jspdf.plugin.autotable',
    'bootstrap-table/tableExport/libs/pdfmake/pdfmake.min',
    'bootstrap-table/tableExport/libs/pdfmake/vfs_fonts',
    'bootstrap-table/tableExport/tableExport.min',
]);


?>


<!-- Modales-->

<?php extend_view(['admin/common/modales-editar'], $data) ?>

<div class="modal fade" id="formCEEmpleado" tabindex="-1" role="dialog" aria-labelledby="formCEEmpleadoLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form enctype="multipart/form-data">
                <div class="modal-header">
                    <h5 class="modal-title" id="formCEEmpleadoLabel">Nuevo Empleado</h5>
                    <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
                <div class="modal-body">

                    <div id="formEmpleado" class="row">

                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-gradient-primary btn-fw btn-submit">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="formIndicativos" tabindex="-1" role="dialog" aria-labelledby="formIndicativosLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header modal-header-recuperar">
                <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0 btn-close-recuperar" data-dismiss="modal" aria-label="Close">
                    <i class="fas fa-times"></i>
                </button>
            </div>

            <div class="modal-body">
                <div class="row">
                    <div class="col-12 col-md-12 my-2">

                        <div class="col-12 col-md-12 text-center mt-2">
                            <h5>Informacion del asesor de ventas</h5>
                        </div>

                        <div class="card-colaborador">
                            <div class="row no-gutters">
                                <div class="col-3 flex-center">
                                    <div id="circuloIndi" class="circulo-vendedor" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="">
                                        <span></span>
                                    </div>
                                </div>
                                <div class="col-6 text-center">
                                    <span id="sNombreEmpIndi"></span>
                                    <div class="w-100"></div>
                                    <span id="sRol" class="font-14"></span>
                                    <div class="w-100"></div>
                                    <span id="sNegocioEmpIndi" class="font-13"></span>
                                </div>
                                <div class="col-3">
                                    <div id="cuadradoIndi" class="cuadraro-supervisor"></div>
                                    <span class="activo-hace">Activo hace <span id="sActivoHaceIndi"></span> </span>
                                </div>
                            </div>
                        </div>

                        <div id="card-indicativos" class="card-colaborador">
                            <div class="row no-gutters">
                                <div class="col-12 col-md-12 text-center">
                                    <p id="titulo-indi" class="title-indicativos">Indicativos</p>
                                </div>

                                <div class="col-6 col-md-7 flex-center">
                                    <div class="border-card mx-1 card-indicativo-1">
                                        <p class="title">Avance</p>
                                        <p id="nAvance">0</p>
                                        <p class="title">Renta Basica</p>
                                        <p id="nRentaBasica">S./0.00</p>
                                    </div>
                                </div>

                                <div class="col-6 col-md-5 flex-center">
                                    <div class="w-100 border-card mx-1 card-indicativo-2">
                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">Compra</div>
                                            <div id="nCompra" class="col-6 value">S./0.00</div>
                                        </div>

                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">Ticket</div>
                                            <div id="nTicket" class="col-6 value">0</div>
                                        </div>

                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">Efectividad</div>
                                            <div id="nEfectividad" class="col-6 value">0%</div>
                                        </div>

                                    </div>
                                </div>

                                <div class="col-12 col-md-12 text-center mt-2">
                                    <p class="title-indicativos">Indicativos Prospectos</p>
                                </div>


                                <div class="col-12 col-md-12 flex-center">
                                    <div class="w-100 border-card mx-1 card-indicativo-3">
                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title"> Citas Hoy </div>
                                            <div id="nCitasCercanas" class="col-6 value">0</div>
                                        </div>

                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">Cierres Hoy</div>
                                            <div id="nTotalCierre" class="col-6 value">0</div>
                                        </div>

                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">Prospectos Hoy</div>
                                            <div id="nProspectosHoyEmpleado" class="col-6 value">0</div>
                                        </div>

                                        <div class="row no-gutters flex-center p-1">
                                            <div class="col-6 title">OPP</div>
                                            <div id="nOportunidadEmpleado" class="col-6 value">0%</div>
                                        </div>

                                    </div>
                                </div>


                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="formFilter" tabindex="-1" role="dialog" aria-labelledby="formFiltersLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form enctype="multipart/form-data">

                <div class="modal-header">
                    <h5 class="modal-title" id="formFiltersLabel">Filtrar</h5>
                    <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                        <i class="fas fa-times"></i>
                    </button>
                </div>

                <div class="modal-body">

                    <div class="row">

                        <div class="col-md-6 col-12">
                            <div class="form-group">

                                <label for="nIdRolFilter" class="col-form-label">Tipo Empleados:</label>

                                <select class="form-control" name="nIdRolFilter" id="nIdRolFilter">
                                    <option value="<?= $nIdRolSupervisor ?>">Supervisor</option>
                                    <option value="<?= $nIdRolAsesorVentas ?>">Asesor de ventas</option>
                                </select>

                            </div>
                        </div>

                        <div class="col-md-6 col-12">
                            <div class="form-group">
                                <label for="nEstadoEmpleadoFilter" class="col-form-label">Estado:</label>
                                <select class="form-control" name="nEstadoEmpleadoFilter" id="nEstadoEmpleadoFilter">
                                    <option value="">TODOS</option>
                                    <option value="1">ACTIVO</option>
                                    <option value="0">DESACTIVO</option>
                                </select>
                            </div>
                        </div>

            

                    </div>


                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-gradient-primary btn-fw btn-submit">Filtrar</button>
                </div>

            </form>

        </div>
    </div>
</div>

<!-- End Modales -->

<!-- BD Empleados -->
<script>
    $(document).ready(function() {

        $("#btnFilter").on("click",function(){
            $("#formFilter").modal("show");
        });

        $("#nIdRolFilter").val('<?=$nIdRolSupervisor?>');

        fncOcultarAside();
        fncDrawTableUsuarios();
        $("#formBDEmpleados").modal("show");

        $('#formCEEmpleado').on('hidden.bs.modal', function() {
            fncClearInputs($("#formCEEmpleado").find("form"));
            fncAgregarOActualizarCamposAdicionalesUsuarios();
        });


        $("#formCEEmpleado").find("form").on('submit', function(event) {

            event.preventDefault();

            var nIdEntidad = $("#nIdRolFilter").val();
            var sEntidad   = "-" + nIdEntidad;

            var nIdRegistro = $("#formCEEmpleado").data("nIdRegistro");

            var nTipoDocumento                =  $("#formCEEmpleado").find("#nTipoDocumento" + sEntidad);
            var sNumeroDocumento              =  $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad);
            var sNombre                       =  $("#formCEEmpleado").find("#sNombre" + sEntidad);
            var sCorreo                       =  $("#formCEEmpleado").find("#sCorreo" + sEntidad);
            var dFechaNacimiento              =  $("#formCEEmpleado").find("#dFechaNacimiento" + sEntidad);
            var nCantidadPersonasDependientes =  $("#formCEEmpleado").find("#nCantidadPersonasDependientes" + sEntidad);
            var nIdEstudios                   =  $("#formCEEmpleado").find("#nIdEstudios" + sEntidad);
            var nIdSituacionEstudios          =  $("#formCEEmpleado").find("#nIdSituacionEstudios" + sEntidad);
            var sCarreraCiclo                 =  $("#formCEEmpleado").find("#sCarreraCiclo" + sEntidad);

            var nIdNegocio                    = <?= $nIdNegocio ?>;
            var nIdRol                        = $("#nIdRolFilter").val();

            var nExperienciaVentas           = $("#formCEEmpleado").find("#nExperienciaVentas" + sEntidad);
            var sRubroExperiencia            = $("#formCEEmpleado").find("#sRubroExperiencia" + sEntidad);

            var nIdEstadoCivil               = $("#formCEEmpleado").find("#nIdEstadoCivil" + sEntidad);
            var nIdSexo                      = $("#formCEEmpleado").find("#nIdSexo" + sEntidad);

            var sImagen                      = $("#formCEEmpleado").find("#sImagen" + sEntidad).length > 0 ?  $("#formCEEmpleado").find("#sImagen" + sEntidad)[0].files[0] : null;
            var sClave                       = $("#formCEEmpleado").find("#sClave" + sEntidad);
            var nEstado                      = $("#formCEEmpleado").find("#nEstado" + sEntidad);

            if (nTipoDocumento.length > 0 && nTipoDocumento.val() == '0') {
                toastr.error('Error. Seleccione un tipo de documento . Porfavor verifique');
                return;
            } else if (sNumeroDocumento.length > 0 && sNumeroDocumento.val() == '') {
                toastr.error('Error. Ingrese un numero de documento. Porfavor verifique');
                return;
            } else if (sNombre.length > 0 && sNombre.val() == '') {
                toastr.error('Error. Ingrese un nombre . Porfavor verifique');
                return;
            } else if (sCorreo.length > 0 && (sCorreo.val() == '' || !fncValidateEmail(sCorreo.val()))) {
                toastr.error('Error. Ingrese un correo con el formato correcto. Porfavor verifique');
                return;
            } else if (dFechaNacimiento.length > 0 && dFechaNacimiento.val() == '') {
                toastr.error('Error. Ingrese un fecha. Porfavor verifique');
                return;
            } else if (nCantidadPersonasDependientes.length > 0 && nCantidadPersonasDependientes.val() == '' || isNaN(nCantidadPersonasDependientes.val()) || nCantidadPersonasDependientes.val() < 0) {
                toastr.error('Error. No ha ingresado la cantidad de personas dependientes o el valor no es correcto. Porfavor verifique');
                return;
            } else if (sClave.length > 0 && sClave.val() == '') {
                toastr.error('Error. Ingrese una contraseña. Porfavor verifique');
                return;
            } else if (nIdEstadoCivil.length > 0 && nIdEstadoCivil.val() == '0') {
                toastr.error('Error. Seleccione un estado civil. Porfavor verifique');
                return;
            } else if (nIdSexo.length > 0 && nIdSexo.val() == '0') {
                toastr.error('Error. Seleccione un tipo de sexo. Porfavor verifique');
                return;
            }


            if (nIdEstudios.length > 0 && nIdEstudios.val() == '1') {

                if (nIdSituacionEstudios.length > 0 && nIdSituacionEstudios.val() == '0') {
                    toastr.error('Error. Seleccione situacion de estudios . Porfavor verifique');
                    return;
                } else if (sCarreraCiclo.length > 0 && sCarreraCiclo.val() == '') {
                    toastr.error('Error. Ingrese situacion de estudios . Porfavor verifique');
                    return;
                }

            }


            if (nExperienciaVentas.length > 0 && nExperienciaVentas.val() == '1') {
                if (sRubroExperiencia.length > 0 && sRubroExperiencia.val() == '') {
                    toastr.error('Error. Ingrese su rubro de experiencia. Porfavor verifique');
                    return;
                }
            }

            var formData = new FormData();
            formData.append('nIdRegistro', nIdRegistro);
            formData.append('nIdNegocio', nIdNegocio);
            formData.append('nIdRol', nIdRol);
            formData.append('nTipoDocumento', nTipoDocumento.length > 0 ? nTipoDocumento.val() : "");
            formData.append('sNumeroDocumento', sNumeroDocumento.length > 0 ? sNumeroDocumento.val() : "");
            formData.append('sNombre', sNombre.length > 0 ? sNombre.val() : "");
            formData.append('sCorreo', sCorreo.length > 0 ? sCorreo.val() : "");

            formData.append('nIdSexo', nIdSexo.length > 0 ? nIdSexo.val() : "");
            formData.append('nIdEstadoCivil', nIdEstadoCivil.length > 0 ? nIdEstadoCivil.val() : "");

            formData.append('dFechaNacimiento', dFechaNacimiento.length > 0 ? dFechaNacimiento.val() : "");
            formData.append('nCantidadPersonasDependientes', nCantidadPersonasDependientes.length > 0 ? nCantidadPersonasDependientes.val() : 0);
            formData.append('nExperienciaVentas', nExperienciaVentas.length > 0 ? nExperienciaVentas.val() : "");
            formData.append('sRubroExperiencia', sRubroExperiencia.length > 0 ? sRubroExperiencia.val() : "");
            formData.append('nIdEstudios', nIdEstudios.length > 0 ? nIdEstudios.val() : "");
            formData.append('nIdSituacionEstudios', nIdSituacionEstudios.length > 0 ? nIdSituacionEstudios.val() : "");
            formData.append('sCarreraCiclo', sCarreraCiclo.length > 0 ? sCarreraCiclo.val() : "");
            formData.append('sClave', sClave.length > 0 ? sClave.val() : "");
            formData.append('sImagen', sImagen);
            formData.append('nEstado', nEstado.length > 0 ? nEstado.val() : "");


            if (<?= $nIdRolSupervisor ?> == $("#nIdRolFilter").val()) {

                // Supervisores

                if ($("#nIdColor" + sEntidad).find("option:selected").val() == '0') {
                    toastr.error('Error. Seleccione un color para el supervisor . Porfavor verifique');
                    return;
                }

                formData.append('nIdColor', $("#nIdColor" + sEntidad).find("option:selected").val());

            } else {

                if ($("#nIdSupervisor" + sEntidad).find("option:selected").val() == '0') {
                    toastr.error('Error. Seleccione un supervisor para el asesor de ventas . Porfavor verifique');
                    return;
                }

                formData.append('nIdSupervisor', $("#nIdSupervisor" + sEntidad).find("option:selected").val());
            }

            fncGrabarUsuario(formData, function(aryData) {
                if (aryData.success) {

                    fncObtenerCamposUsuariosByFilter();
                    $("#formCEEmpleado").modal("hide");
                } else {
                    toastr.error(aryData.error);
                }
            });


        });

        $("#formFilter").find("form").on("submit",function(event){
            event.preventDefault();
            fncDrawTableUsuarios();

        });



    });

    // Funciones Auxiliares


    window.fncDrawTableUsuarios = function() {

        var jsnData = {
            nIdRol      : $("#nIdRolFilter").val(),
            nEstado     : $("#nEstadoEmpleadoFilter").val() == '' ? null : $("#nEstadoEmpleadoFilter").val(),
            nIdNegocio  : <?= $nIdNegocio ?>,
            nRol        : <?= $user["nIdRol"] ?>
        };

        $("#sTituloEmpleado").html($("#nIdRolFilter").find("option:selected").text() + " : ");

        fncObtenerCamposUsuarios(jsnData, (aryData) => {

            if (aryData.success) {

                var aryData = aryData.aryData;
                var sHtml = ``;

                sHtml = `<tr>`;

                sHtml += `<th data-field="sAcciones">Acciones</th>`;


                sHtml += `<th data-field="sColor">Color</th>`;


                aryData.forEach(aryElement => {
                    sHtml += `<th data-field="${aryElement.sNombre}">${aryElement.sNombreUsuario}</th>`;
                });

                sHtml += `<tr>`;

                $("#tblBDEmpleados").bootstrapTable("destroy");

                setTimeout(() => {
                    $("#tblBDEmpleados").find("thead").html(sHtml);
                    setTimeout(() => {


                        $("#tblBDEmpleados").bootstrapTable();

                        var nIdEntidad  = $("#nIdRolFilter").val();
                        var sEntidad    = '-' + nIdEntidad;

                        fncPopulateUsuarios(jsnData, function(aryData) {
                            if (aryData.success) {

                                $("#tblBDEmpleados").bootstrapTable("load", aryData.aryData);

                                // Llmar alos campos del formulario

                                fncDrawEmpleado((bStatus) => {

                                    // Se carga el formulario 

                                    $("#btnCrearEmpleado").on('click', function() {
                                        $('#formCEEmpleado').data("nIdRegistro", 0);
                                        $('#formCEEmpleado').find(".modal-title").html("Nuevo " + fncUc($("#nIdRolFilter").find("option:selected").text()));
                                        $('#formCEEmpleado').modal("show");
                                    });

                                    // Ocultamos el estado ya que no tiene sentido que el usuario lo ingrese 
                                    // Si todo esta cooreecto agrergo los eventos

                                    $("#formCEEmpleado").find("#nIdEstudios" + sEntidad).on('change', function() {

                                        switch ($(this).val()) {
                                            case '0':
                                            case '602':
                                            case '605':
                                                // Educaccion Basica y ninguno
                                                $("#formCEEmpleado").find("#content-nIdSituacionEstudios" + sEntidad).hide();
                                                $("#formCEEmpleado").find("#content-sCarreraCiclo" + sEntidad).hide();
                                                break;
                                            case '604':
                                            case '603':
                                                // Educaccion Superior y teecnico
                                                $("#formCEEmpleado").find("#content-nIdSituacionEstudios" + sEntidad).show();
                                                $("#formCEEmpleado").find("#content-sCarreraCiclo" + sEntidad).show();
                                                break;

                                        }

                                    });

                                    $("#formCEEmpleado").find("#nExperienciaVentas" + sEntidad).on('change', function() {
                                        if ($(this).val() == 1) {
                                            $("#formCEEmpleado").find("#content-sRubroExperiencia" + sEntidad).show();
                                        } else {
                                            $("#formCEEmpleado").find("#content-sRubroExperiencia" + sEntidad).hide();
                                        }
                                    });

                                    $("#formCEEmpleado").find("#nTipoDocumento" + sEntidad).change(function() {

                                        if ($(this).val() > 0) {
                                            fncMaxLengthTypeDocument($(this).find('option:selected').text().trim().toUpperCase(), "#sNumeroDocumento" + sEntidad);
                                        }

                                        $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val("").trigger("keyup");

                                    });

                                    $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).on('keyup change', function() {

                                        switch ( $("#formCEEmpleado").find("#nTipoDocumento" + sEntidad).find("option:selected").text()) {

                                            case 'RUC':

                                                if ($("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val().length == 11) {

                                                    // Lanzamos el evento
                                                    var jsnData = {
                                                        sTipo: "ruc",
                                                        sNumeroDoc: $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val()
                                                    };

                                                    fncBuscarDocument(jsnData, function(aryData) {
                                                        if (aryData.success) {
                                                            $("#formCEEmpleado").find("#sNombre" + sEntidad).val(aryData.success.razonSocial);
                                                        }
                                                    });

                                                }

                                                break;

                                            case 'DNI':
                                                if ($("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val().length == 7 || $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val().length == 8) {

                                                    // Lanzamos el evento
                                                    var jsnData = {
                                                        sTipo: "dni",
                                                        sNumeroDoc: $("#formCEEmpleado").find("#sNumeroDocumento" + sEntidad).val()
                                                    };

                                                    fncBuscarDocument(jsnData, function(aryData) {
                                                        if (aryData.success) {
                                                            $("#formCEEmpleado").find("#sNombre" + sEntidad).val(aryData.success.razonSocial);
                                                        }
                                                    });

                                                }
                                                break;

                                        }


                                    });

                                    $("#formCEEmpleado").find("#nIdSituacionEstudios" + sEntidad).on('change', function() {
                                        if ($(this).val() == '608') {
                                            $("#formCEEmpleado").find("label[for='sCarreraCiclo" + sEntidad + "']").html("Carrera");
                                        } else {
                                            $("#formCEEmpleado").find("label[for='sCarreraCiclo" + sEntidad + "']").html("Carrera y ciclo");
                                        }
                                    });

                                    $("#formCEEmpleado").find("#content-sCorreo" + sEntidad).removeClass("col-md-12");
                                    $("#formCEEmpleado").find("#content-sCorreo" + sEntidad).addClass("col-md-6");

                                    $("#formCEEmpleado").find("#nIdEstudios" + sEntidad).trigger("change");

                                    fncAgregarOActualizarCamposAdicionalesUsuarios();
                                    fncEventFile();
                                });

                                $("#formFilter").modal("hide");

                            } else {
                                toastr.error(aryData.error);
                            }
                        });

                    }, 200);
                }, 1000);

            } else {
                toastr.error(aryData.error);
            }
        });
    }

    function fncAgregarOActualizarCamposAdicionalesUsuarios() {

        // Campo adicional para supervisor o asesor de ventas 


        var nIdEntidad = $("#nIdRolFilter").val();
        var sEntidad = '-' + nIdEntidad;

        if (<?= $nIdRolSupervisor ?> == $("#nIdRolFilter").val()) {

            // Formulario Supervisor - Agregar el item color

            var jsnData = {
                nIdNegocio: <?= $nIdNegocio ?>
            };


            fncObtenerColores(jsnData, (aryData) => {
                if (aryData.success) {

                    var sNameOrId = "nIdColor" + sEntidad;
                    var aryData = aryData.aryData;
                    var sOptionsComboPrincipal = ``; // Este sirve para actualizar los colores en el modal de invitar 

                    if ($('#content-' + sNameOrId).length > 0) $('#content-' + sNameOrId).remove();

                    var sHtml = `
                         <div id="content-${sNameOrId}" class="col-12 col-md-6">
                                 <div class="form-group"><label for="${sNameOrId}" class="col-form-label">Color</label>
                                 <select class="form-control" name="${sNameOrId}" id="${sNameOrId}">
                                 `;

                    sHtml += `<option value="0">SELECCIONAR</option>`;
                    sOptionsComboPrincipal += `<option value="0">SELECCIONAR</option>`;
                    aryData.forEach(aryItem => {
                        sHtml += `<option value="${aryItem.nIdCatalogoTabla}">${aryItem.sDescripcionLargaItem}</option>`;
                        sOptionsComboPrincipal += `<option value="${aryItem.nIdCatalogoTabla}">${aryItem.sDescripcionLargaItem}</option>`;
                    });

                    sHtml += `    
                                 </select>
                             </div>
                         </div>
                         `;

                    $("#formEmpleado").prepend(sHtml);
                    $("#nIdColor").html(sOptionsComboPrincipal);

                } else {
                    toastr.error(aryData.error);
                }
            });


        } else {

            // Formulario Asesor de ventas

            var jsnData = {
                nIdNegocio: <?= $nIdNegocio ?>,
                nIdRol: <?= $nIdRolSupervisor ?>
            };

            fncPopulateUsuarios(jsnData, (aryData) => {

                if (aryData.success) {

                    var sNameOrId = "nIdSupervisor" + sEntidad;
                    var aryData = aryData.aryData;

                    if ($('#content-' + sNameOrId).length > 0) $('#content-' + sNameOrId).remove();

 
                    var sHtml = `
                        <div id="content-${sNameOrId}" class="col-12 col-md-6">
                                <div class="form-group"><label for="${sNameOrId}" class="col-form-label">Supervisor</label>
                                <select class="form-control" name="${sNameOrId}" id="${sNameOrId}">
                                `;

                    sHtml += `<option value="0">SELECCIONAR</option>`;
                     aryData.forEach(aryItem => {
                        sHtml += `<option value="${aryItem.nIdUsuario}">${aryItem.sNombre} - ${aryItem.sNombreColor} </option>`;
                     });

                    sHtml += `    
                                </select>
                            </div>
                        </div>
                        `;

                    $("#formEmpleado").prepend(sHtml);
 

                } else {

                    toastr.error(aryData.error);

                }


            });



        }

    }

    function fncDrawEmpleado(fncCallback) {

        var nIdEntidad = $("#nIdRolFilter").val();

        var jsnData = {
            nIdEntidad: nIdEntidad,
            nIdNegocio: <?= $nIdNegocio ?>
        };

        fncObtenerDataForm(jsnData, function(aryData) {
            $("#formEmpleado").html(fncBuildForm(aryData));
            fncCallback(true);
        });

    }
 

    function fncCambiarEstadoEmpleado(nIdRegistro, nNuevoEstado) {

        var sEstado = nNuevoEstado == '1' ? 'mostrará' : 'ocultará';

        if (confirm('Esta acción ' + sEstado + ' el registro en todo el sistema. ¿ Esta seguro de continuar ?', )) {

            var jsnData = {
                nIdRegistro: nIdRegistro,
                nEstado: nNuevoEstado
            };

            fncEjecutarCambiarEstado(jsnData, (aryData) => {
                if (aryData.success) {
                    fncObtenerCamposUsuariosByFilter();
                } else {
                    toastr.error(aryData.error);
                }
            });
        }

    }

    function fncObtenerCamposUsuariosByFilter() {

        var jsnData = {
            nIdRol      : $("#nIdRolFilter").val(),
            nIdNegocio  : <?= $nIdNegocio ?>
        };

        fncPopulateUsuarios(jsnData, function(aryData) {
            if (aryData.success) {

                $("#tblBDEmpleados").bootstrapTable("load", aryData.aryData);
                fncAgregarOActualizarCamposAdicionalesUsuarios();
            } else {
                toastr.error(aryData.error);
            }
        });

    }

    function fncMostrarEmpleado(nIdRegistro , sOpcion ) {

        $( "#formCEEmpleado" ).data("nIdRegistro",nIdRegistro);

        var jsnData = {
            nIdRegistro: nIdRegistro
        };

        fncBuscarUsuario(jsnData, function(aryResponse){
            
                if (aryResponse.success) {

                    var nIdEntidad = $("#nIdRolFilter").find("option:selected").val();
                    var sEntidad   = "-" + nIdEntidad;
                    console.log(sEntidad);
                    var aryData = aryResponse.aryData;

                    if( $( "#nIdColor" + sEntidad ).length > 0 ) {
                        
                        $( "#nIdColor"  + sEntidad ).append(`<option value="${aryData.nIdColor}" >${aryData.sColorSuper}</option>`);

                        setTimeout(() => {
                            $( "#nIdColor"  + sEntidad ).val(aryData.nIdColor).trigger("change");
                        }, 500);

                    } 
                     
                    if( $("#formCEEmpleado").find( "#nIdSupervisor" + sEntidad ).length > 0 )  $("#formCEEmpleado").find( "#nIdSupervisor" + sEntidad ).val( aryData.nIdSupervisor ); 
                    if( $("#formCEEmpleado").find( "#nTipoDocumento" + sEntidad ).length > 0 )  $("#formCEEmpleado").find( "#nTipoDocumento" + sEntidad ).val( aryData.nTipoDocumento ); 
                    if( $("#formCEEmpleado").find( "#sNumeroDocumento" + sEntidad ).length > 0 )  $("#formCEEmpleado").find( "#sNumeroDocumento" + sEntidad ).val( aryData.sNumeroDocumento ); 
                    if( $("#formCEEmpleado").find( "#sNombre" + sEntidad ).length > 0 ) $("#formCEEmpleado").find( "#sNombre" + sEntidad ).val( aryData.sNombre ); 
                    if( $("#formCEEmpleado").find( "#sCorreo" + sEntidad ).length > 0 ) $("#formCEEmpleado").find( "#sCorreo" + sEntidad ).val( aryData.sCorreo ); 

                    if( $("#formCEEmpleado").find( "#nIdSexo" + sEntidad ).length > 0 )  $("#formCEEmpleado").find( "#nIdSexo" + sEntidad ).val( aryData.nIdSexo ); 
                    if( $("#formCEEmpleado").find( "#nIdEstadoCivil" + sEntidad ).length > 0 ) $("#formCEEmpleado").find( "#nIdEstadoCivil" + sEntidad ).val( aryData.nIdEstadoCivil ); 

                    if( $("#formCEEmpleado").find( "#nExperienciaVentas" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#nExperienciaVentas" + sEntidad ).val( aryData.nExperienciaVentas ).trigger("change"); 
                    if( $("#formCEEmpleado").find( "#sRubroExperiencia" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#sRubroExperiencia" + sEntidad ).val( aryData.sRubroExperiencia ); 
                    if( $("#formCEEmpleado").find( "#dFechaNacimiento" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#dFechaNacimiento" + sEntidad ).val( aryData.dFechaNacimiento ); 
                    if( $("#formCEEmpleado").find( "#nCantidadPersonasDependientes" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#nCantidadPersonasDependientes" + sEntidad ).val( aryData.nCantidadPersonasDependientes ); 
                    if( $("#formCEEmpleado").find( "#nIdEstudios" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#nIdEstudios" + sEntidad ).val( aryData.nIdEstudios ); 
                    if( $("#formCEEmpleado").find( "#nIdSituacionEstudios" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#nIdSituacionEstudios" + sEntidad ).val( aryData.nIdSituacionEstudios ); 
                    if( $("#formCEEmpleado").find( "#sCarreraCiclo" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#sCarreraCiclo" + sEntidad ).val( aryData.sCarreraCiclo ); 
                    if( $("#formCEEmpleado").find( "#nEstado" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#nEstado" + sEntidad ).val( aryData.nEstado ); 
                    if( $("#formCEEmpleado").find( "#sClave" + sEntidad ).length > 0 )   $("#formCEEmpleado").find( "#sClave" + sEntidad ).val( aryData.sClave ); 
                    if( $("#formCEEmpleado").find( "#sImagen" + sEntidad ).length > 0 ) {
                        if( aryData.sImagen.length > 0){
                            $("#formCEEmpleado").find( "#sImagen" + sEntidad ).parent().find(".custom-file-label").html( aryData.sImagen ); 
                        }
                    }


                   var sTitle = fncUc($("#nIdRolFilter").find("option:selected").text());

                    if(sOpcion == 'ver'){
                        fncViewForm("#formCEEmpleado" , "Ver " + sTitle);
                    } else {
                        fncEditForm("#formCEEmpleado" , "Editar "  + sTitle);
                    }

                    $("#formCEEmpleado").modal("show");


                } else {
                    toastr.error(aryData.error);
                }
        });

    }

    window.fncVerEmpleado = (nIdUsuario)=>{
           
           var jsnData = {
               nIdRegistro : nIdUsuario,
           };

           fncMostrarRegistroCard(jsnData,true,(aryData)=>{
            if(aryData.success){
                var aryData= aryData.aryData ; 

                $("#circuloIndi").html(aryData.sUsuarioCorto);
                $("#circuloIndi").attr("data-original-title",aryData.sNombre);
                $("#sNombreEmpIndi").html(aryData.sNombre);
                $("#sRol").html(aryData.sRol);
                $("#sNegocioEmpIndi").html(aryData.sNombreNegocio);
                $("#cuadradoIndi").addClass("fondo-"+aryData.sColorSuperEmpleado.toLowerCase());
                $("#sActivoHaceIndi").html(aryData.sUltimoAcceso);

                var dDesde =  moment().startOf('month').format('DD/MM/YYYY');
                var dHasta =  moment().format('DD/MM/YYYY');

                var jsnData = {
                    nIdNegocio   : <?= $nIdNegocio ?>,
                    nIdUsuario  : nIdUsuario,
                    dDesde       : dDesde,
                    dHasta       : dHasta,
                };

                fncGetProspectos(jsnData,true,(aryData)=>{

                    var aryIndicativos = aryData.aryIndicativos;
                 
                    $("#nAvance").html(aryIndicativos.nAvance);
                    $("#nRentaBasica").html(aryIndicativos.nRentaBasica);
                    $("#nCompra").html(aryIndicativos.nCompra);
                    $("#nTicket").html(aryIndicativos.nTicket);
                    $("#nEfectividad").html(aryIndicativos.nEfectividad);
                    $("#nOportunidadEmpleado").html(aryIndicativos.nOportunidad);

                    if(dDesde != "" &&  dHasta !="" ){
                        $("#titulo-indi").html("Indicativos <br/> <span style='font-size:15px;'> " + dDesde +  " - " + dHasta  +"</span>");
                    } else {
                        $("#titulo-indi").html("Indicativos");
                    }
                    
                    var jsnData = {
                        nIdNegocio   : <?= $nIdNegocio ?>,
                        nIdUsuario  : nIdUsuario,
                    };

                    fncIndicativosHoy(jsnData,false,(aryData)=>{

                        if(aryData.success){
                            
                            var aryData = aryData.aryData;

                            $("#nCitasCercanas").html(aryData.nCantidadCitasHoy);
                            $("#nTotalCierre").html(aryData.nCierreHoy);
                            $("#nProspectosHoyEmpleado").html(aryData.nProspectosHoy);
                            $("#formIndicativos").modal("show");            

                        } else {
                            toastr.error(aryData.error);
                        }
                 
                    });


                });
            }else{
                toastr.error(aryData.error);
            }

           });

    }




    // LLamadas al servidor 

    function fncGrabarUsuario(formData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/usuarios/fncGrabarUsuario',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncObtenerCamposUsuarios(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncObtenerCamposUsuarios',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncObtenerColores(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncObtenerColores',
            data: jsnData,
            beforeSend: function() {
                //fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                //fncOcultarLoader();
            }
        });
    }

    window.fncObtenerDataForm = (jsnData, fncCallback) => {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'formularios/fncBuildForm',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    window.fncBuscarUsuario = (jsnData, fncCallback) => {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncMostrarRegistro',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    window.fncEjecutarCambiarEstado = (jsnData, fncCallback) => {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncCambiarEstado',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }



    function fncGetProspectos(jsnData, bShowLoader= true , fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/prospecto/fncGetProspectos',
            data: jsnData,
            beforeSend: function() {
             if(bShowLoader) fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                if(bShowLoader) fncOcultarLoader();
            } ,
            error: function(error) {
                alert( JSON.stringify(error) );
            }
        });
    }

    function fncMostrarRegistroCard(jsnData, bShowLoader= true , fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncMostrarRegistroCard',
            data: jsnData,
            beforeSend: function() {
             if(bShowLoader) fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                if(bShowLoader) fncOcultarLoader();
            }
        });
    }
  
    function fncIndicativosHoy(jsnData, bShowLoader= true , fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/prospecto/fncIndicativosHoy',
            data: jsnData,
            beforeSend: function() {
             if(bShowLoader) fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                if(bShowLoader) fncOcultarLoader();
            }
        });
    }

    function fncPopulateUsuarios(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'usuarios/fncPopulate',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncBuscarDocument(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root +  'api/'+ jsnData.sTipo +'/' + jsnData.sNumeroDoc ,
            beforeSend: function () {
                fncMostrarLoader();
            },
            success: function (data) {
                fncCallback(data);
            },
            complete: function () {
                fncOcultarLoader();
            }
        });
    }
</script>
<!--  BD Empleados -->




</html>