<!DOCTYPE html>
<html class="no-js h-100" lang="es">

<head>
    <?php extend_view(['admin/common/head'], $data) ?>
    <?php load_style(['bootstrap', 'jquery-ui', 'admin/style', 'admin/shards-dashboards.1.1.0.min']); ?>
    <?php load_style_plugin(['toast/toastr.min']); ?>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>

    <div class="page-loader">
        <div class="loader-dual-ring"></div>
    </div>

    <div class="container-fluid">

        <div class="row">


            <main class="main-content col-lg-12 col-md-9 col-sm-12 p-0">

                <?php extend_view(['admin/common/navbar'], $data) ?>

                <div class="main-content-container container-fluid px-4">

                    <div class="container">
                        <div class="page-header row no-gutters py-4">
                            <div class="col-lg-12 col-md-12 col-sm-12 mb-4">
                                <div class="card card-small">
                                    <div class="card-header border-bottom">
                                        <div class="d-flex align-items-center bd-highlight">
                                            <div class="flex-grow-1 bd-highlight">
                                                <h5 class="m-0">Seleccione su negocio :</h5>
                                            </div>
                                            <div class="bd-highlight">
                                                <button data-toggle="modal" id="btnCrearNegocio" class="btn btn-gradient-primary btn-rounded btn-icon">
                                                    <i class="fas fa-plus-circle"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="card-body py-4">
                                        <div class="row" id="list-negocios">

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>

            </main>
        </div>
    </div>



    <!-- Modales -->

    <?php extend_view(['admin/common/modales-editar'], $data) ?>

    <div class="modal fade" enctype="multipart/form-data" id="formNegocio" tabindex="-1" role="dialog" aria-labelledby="formNegocioLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formNegocioLabel">Nuevo Negocio</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">


                        <ul class="nav nav-tabs" id="myTab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">General</a>
                            </li>
                            <li class="nav-item" role="presentation">
                                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Controles</a>
                            </li>
                        </ul>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane  show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">

                                 
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="sNombre" class="col-form-label">Nombre:</label>
                                            <input type="text" class="form-control" id="sNombre" autocomplete="off" name="sNombre">
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="sDireccion" class="col-form-label">Direccion:</label>
                                            <input type="text" class="form-control" id="sDireccion" autocomplete="off" name="sDireccion">
                                        </div>
                                    </div>


                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="nIdPais" class="col-form-label">Pais:</label>
                                            <select class="form-control" name="nIdPais" id="nIdPais">
                                                <option value="0">Seleccionar</option>
                                                <?php foreach ($aryPaises as $aryLoop) : ?>
                                                    <option value="<?= $aryLoop['nIdPais'] ?>"><?= $aryLoop['sNombre'] ?></option>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                    </div>


                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="sCiudad" class="col-form-label">Ciudad:</label>
                                            <input type="text" class="form-control" id="sCiudad" autocomplete="off" name="sCiudad">
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="nIdMoneda" class="col-form-label">Moneda:</label>
                                            <select class="form-control" name="nIdMoneda" id="nIdMoneda">
                                                <option value="0">Seleccionar</option>
                                                <?php foreach ($aryMoneda as $aryLoop) : ?>
                                                    <option value="<?= $aryLoop['nIdCatalogoTabla'] ?>"><?= $aryLoop['sDescripcionLargaItem'] ?></option>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="nPorcentajeTributo" class="col-form-label" title="Porcentaje de tributo segun el pais, en caso no requiera colocar en 0">Porcentaje Tributo:</label>
                                            <input type="text" class="form-control" id="nPorcentajeTributo" autocomplete="off" name="nPorcentajeTributo">
                                        </div>
                                    </div>


                                    <div class="col-md-12 col-12">
                                        <div class="form-group">
                                            <label for="sImagen" class="col-form-label">Imagen:</label>
                                            <div class="input-group">
                                                <div class="custom-file">
                                                    <input type="file" class="custom-file-input" id="sImagen" accept="image/*" lang="es" name="sImagen">
                                                    <label class="custom-file-label" for="sImagen">Elija el archivo</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div id="content-nTipoProspecto" class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="nTipoProspecto" class="col-form-label">Tipo De Prospecto:</label>
                                            <select class="form-control" name="nTipoProspecto" id="nTipoProspecto">
                                                <option value="0">Seleccionar</option>
                                                <?php foreach ($aryTipoProspectos as $aryTipoProspecto) : ?>
                                                    <option value="<?= $aryTipoProspecto['nIdCatalogoTabla'] ?>"><?= $aryTipoProspecto['sDescripcionLargaItem'] ?></option>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                    </div>


                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <label for="nEstado" class="col-form-label">Estado:</label>
                                            <select class="form-control" name="nEstado" id="nEstado">
                                                <option value="1">Activo</option>
                                                <option value="0">Desactivo</option>
                                            </select>
                                        </div>
                                    </div>

                                </div>


                            </div>
                            <div class="tab-pane " id="profile" role="tabpanel" aria-labelledby="profile-tab">

                                <div class="row py-2">
                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <span>Cliente
                                                <a class="edit-controles" data-toggle="modal" data-target="#formCliente"><i class="fas fa-pen"></i></a></span>
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <span>Vendedores <a class="edit-controles" data-toggle="modal" data-target="#formVendedores"><i class="fas fa-pen"></i></a></span>
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <span>Productos o servicios <a class="edit-controles" data-toggle="modal" data-target="#formProductosoServicios"><i class="fas fa-pen"></i></a></span>
                                        </div>
                                    </div>

                                    <div class="col-md-6 col-12">
                                        <div class="form-group">
                                            <span>Supervisores <a class="edit-controles" data-toggle="modal" data-target="#formSupervisores"><i class="fas fa-pen"></i></a></span>
                                        </div>
                                    </div>

                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-gradient-primary btn-fw btn-submit">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formCliente" tabindex="-1" role="dialog" aria-labelledby="formClienteLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formClienteLabel">Editar Control cliente</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">


                        <div class="row  ml-content-custom-switch w-100">

                            <?php foreach ($aryConfigClientes as $aryConfigCliente) : ?>
                                <!-- Ocultamos Tipo de documento y Apellidos -->
                                <?php $sClass = in_array($aryConfigCliente['nIdCampoEntidad'], [1, 5]) ? 'd-none' : ''; ?>
                                <div class="col-12 col-md-6 my-2 <?= $sClass ?>">
                                    <div class="custom-control custom-switch ">
                                        <input type="checkbox" name="aryConfiguracionCliente[]" class="custom-control-input" id="chk<?= $aryConfigCliente['nIdCampoEntidad'] ?>" checked="checked" value="<?= $aryConfigCliente['nIdCampoEntidad'] ?>">
                                        <label class="custom-control-label" for="chk<?= $aryConfigCliente['nIdCampoEntidad'] ?>"><?= $aryConfigCliente['sNombreUsuario'] ?></label>
                                    </div>
                                </div>
                            <?php endforeach ?>


                        </div>


                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formVendedores" tabindex="-1" role="dialog" aria-labelledby="formVendedoresLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formVendedoresLabel">Editar Control Vendedor</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">


                        <div class="row  ml-content-custom-switch w-100">

                            <?php foreach ($aryConfigVendedores as $aryConfigVendedor) : ?>
                                <?php $sClass = in_array($aryConfigVendedor['nIdCampoEntidad'], [16, 20]) ? 'd-none' : ''; ?>
                                <div class="col-12 col-md-6 my-2 <?= $sClass ?>">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" name="aryConfiguracionVendedores[]" class="custom-control-input" id="chk<?= $aryConfigVendedor['nIdCampoEntidad'] ?>" checked="checked" value="<?= $aryConfigVendedor['nIdCampoEntidad'] ?>">
                                        <label class="custom-control-label" for="chk<?= $aryConfigVendedor['nIdCampoEntidad'] ?>"><?= $aryConfigVendedor['sNombreUsuario'] ?></label>
                                    </div>
                                </div>
                            <?php endforeach ?>


                        </div>


                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formProductosoServicios" tabindex="-1" role="dialog" aria-labelledby="formProductosoServiciosLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formProductosoServiciossLabel">Editar Control Productos</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">


                        <div class="row  ml-content-custom-switch w-100">

                            <?php foreach ($aryConfigCatalogos as $aryConfigCatalogo) : ?>
                                <div class="col-12 col-md-6 my-2">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" name="aryConfiguracionCatalogo[]" class="custom-control-input" id="chk<?= $aryConfigCatalogo['nIdCampoEntidad'] ?>" checked="checked" value="<?= $aryConfigCatalogo['nIdCampoEntidad'] ?>">
                                        <label class="custom-control-label" for="chk<?= $aryConfigCatalogo['nIdCampoEntidad'] ?>"><?= $aryConfigCatalogo['sNombreUsuario'] ?></label>
                                    </div>
                                </div>
                            <?php endforeach ?>


                        </div>


                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formSupervisores" tabindex="-1" role="dialog" aria-labelledby="formSupervisoresLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formSupervisoresLabel">Editar Control Supervisor</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">


                        <div class="row  ml-content-custom-switch w-100">

                            <?php foreach ($aryConfigSupervisores as $aryConfigSupervisor) : ?>
                                <?php $sClass = in_array($aryConfigSupervisor['nIdCampoEntidad'], [28, 31]) ? 'd-none' : ''; ?>
                                <div class="col-12 col-md-6 my-2 <?= $sClass ?>">
                                    <div class="custom-control custom-switch">
                                        <input type="checkbox" name="aryConfiguracionSupervisor[]" class="custom-control-input" id="chk<?= $aryConfigSupervisor['nIdCampoEntidad'] ?>" checked="checked" value="<?= $aryConfigSupervisor['nIdCampoEntidad'] ?>">
                                        <label class="custom-control-label" for="chk<?= $aryConfigSupervisor['nIdCampoEntidad'] ?>"><?= $aryConfigSupervisor['sNombreUsuario'] ?></label>
                                    </div>
                                </div>
                            <?php endforeach ?>


                        </div>


                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formInvitarUsuario" tabindex="-1" role="dialog" aria-labelledby="formInvitarUsuarioLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formInvitarUsuarioLabel">Invitar usuario</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row">


                            <div id="content-sCorreoInvitacion" class="col-md-6 col-12">
                                <div class="form-group">
                                    <label for="sCorreoInvitacion" class="col-form-label">Correo:</label>
                                    <input type="email" class="form-control" id="sCorreoInvitacion" autocomplete="off" name="sCorreoInvitacion">
                                </div>
                            </div>

                            <div id="content-nRol" class="col-md-6 col-12">
                                <div class="form-group">
                                    <label for="nRol" class="col-form-label">Rol</label>
                                    <select class="form-control" name="nRol" id="nRol">
                                        <option value="2">Visitante</option>
                                        <option value="1">Administrador</option>
                                    </select>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-gradient-primary btn-fw btn-submit">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formListarUsuarios" tabindex="-1" role="dialog" aria-labelledby="formListarUsuariosLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h5 class="modal-title" id="formListarUsuariosLabel">Listar usuarios</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row flex-center " id="lista-usuarios">



                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <!-- Fin de modales -->






</body>


<?php extend_view(['admin/common/scripts'], $data) ?>
<?php load_script(['jquery', 'jquery-ui', 'popper', 'bootstrap', 'admin/custom', 'admin/functions', 'admin/edit-user-empleado', 'admin/app']); ?>
<?php load_script_plugin(['toast/toastr.min']); ?>

<script>
    $(function() {

        // Formulario Negocios 

        // Esta funcion sirve para activar el hijo ejemplo si se activa nombre por ende tambien apellidos y viceversa
        //Clientes
        fncDrawNegocios();

        fncActDescCheck("#chk2", "#chk1");
        fncActDescCheck("#chk4", "#chk5");

        //Vendedores
        fncActDescCheck("#chk17", "#chk16");
        fncActDescCheck("#chk19", "#chk20");

        //Supervisores
        fncActDescCheck("#chk29", "#chk28");
        fncActDescCheck("#chk30", "#chk31");
        fncValidateUser();

        $("#btnCrearNegocio").on('click', function() {
            fncCleanAll();
            $("#formNegocio").find(".modal-title").html('Nuevo Negocio');
            $("#sNombre").data("nIdRegistro", 0);
            $("#nPorcentajeTributo").val(0);
            $("#content-nTipoProspecto").show();
            $("#formNegocio").modal("show");
        });

        $("#formNegocio").find('form').on('submit', function(event) {

            event.preventDefault();

            var nIdRegistro = $("#sNombre").data("nIdRegistro");
            var sNombre = $("#sNombre").val().trim();
            var sDireccion = $("#sDireccion").val().trim();
            var sImagen = $("#sImagen")[0].files[0];
            var nTipoProspecto = $("#nTipoProspecto").val().trim();
            var nEstado = $("#nEstado").val();

            var nIdPais = $("#nIdPais").val();
            var sCiudad = $("#sCiudad").val().trim();
            var nIdMoneda = $("#nIdMoneda").val();
            var nPorcentajeTributo = $("#nPorcentajeTributo").val();


            var aryConfiguracionCliente = fncGetAryCampos("input[name='aryConfiguracionCliente[]'");
            var aryConfiguracionCatalogo = fncGetAryCampos("input[name='aryConfiguracionCatalogo[]'");
            var aryConfiguracionVendedores = fncGetAryCampos("input[name='aryConfiguracionVendedores[]'");
            var aryConfiguracionSupervisor = fncGetAryCampos("input[name='aryConfiguracionSupervisor[]'");


            if (sNombre == '') {
                toastr.error('Error. Debe ingresar el nombre del negocio. Porfavor verifique');
                return false;
            } else if (sDireccion == '') {
                toastr.error('Error. Debe ingresar el nombre del negocio. Porfavor verifique');
                return false;
            } else if (nTipoProspecto == '0') {
                toastr.error('Error. Debe seleccionar un tipo de prospecto del negocio. Porfavor verifique');
                return false;
            } else if (nIdPais == '0') {
                toastr.error('Error. Debe seleccionar un pais para el negocio. Porfavor verifique');
                return false;
            }  else if (sCiudad == '') {
                toastr.error('Error. Debe ingresar el nombre de la ciudad. Porfavor verifique');
                return false;
            }  else if (nIdMoneda == '0') {
                toastr.error('Error. Debe seleccionar la moneda. Porfavor verifique');
                return false;
            } 

            var formData = new FormData();
            formData.append('nIdRegistro', nIdRegistro);
            formData.append('sNombre', sNombre);
            formData.append('sDireccion', sDireccion);
            formData.append('sImagen', sImagen);
            formData.append('nTipoProspecto', nTipoProspecto);
            formData.append('nEstado', parseInt(nEstado));
            formData.append('aryConfiguracionCliente', JSON.stringify(aryConfiguracionCliente));
            formData.append('aryConfiguracionCatalogo', JSON.stringify(aryConfiguracionCatalogo));
            formData.append('aryConfiguracionVendedores', JSON.stringify(aryConfiguracionVendedores));
            formData.append('aryConfiguracionSupervisor', JSON.stringify(aryConfiguracionSupervisor));

            formData.append('nIdPais', nIdPais);
            formData.append('sCiudad', sCiudad);
            formData.append('nIdMoneda', nIdMoneda);
            formData.append('nPorcentajeTributo', (nPorcentajeTributo == '' || isNaN(nPorcentajeTributo) || nPorcentajeTributo < 0 ? 0 : nPorcentajeTributo));

            fncGrabarNegocio(formData, function(aryData) {
                if (aryData.success) {
                    fncCleanAll();
                    fncDrawNegocios();
                    $("#formNegocio").modal("hide");
                    toastr.success(aryData.success);
                } else {
                    toastr.error(aryData.error);
                }
            });


        });

        // Fin de Formulario Negocios 

    });

    // Funciones de la tabla o layout Principal 

    function fncEliminarRegistro(nIdRegistro) {
        if (confirm('Esta acción eliminará permanentemente el registro y no podrá deshacerse. ¿ Esta seguro de continuar ?')) {

            var jsnData = {
                nIdRegistro: nIdRegistro
            };

            fncEjecutarEliminarRegistro(jsnData, function(aryData) {

                if (aryData.success) {
                    fncDrawNegocios();
                    toastr.success(aryData.success);
                } else {
                    toastr.error(aryData.error);
                }

            });
        }
    }

    function fncEliminarInvitacion(nIdNegocio, nIdUsuario) {
        if (confirm('Esta acción eliminará permanentemente la invitacion y no podrá deshacerse. ¿ Esta seguro de continuar ?')) {

            var jsnData = {
                nIdNegocio: nIdNegocio,
                nIdUsuario: nIdUsuario
            };

            fncEjecutarEliminarUsuarioNegocio(jsnData, function(aryData) {

                if (aryData.success) {
                    fncDrawNegocios();
                    toastr.success(aryData.success);
                } else {
                    toastr.error(aryData.error);
                }

            });
        }
    }

    function fncMostrarRegistro(nIdRegistro) {

        $("#sNombre").data("nIdRegistro", nIdRegistro);
        $("#content-nTipoProspecto").hide();

        var jsnData = {
            nIdRegistro: nIdRegistro
        };
        console.log(0);

        fncBuscarRegistro(jsnData, function(aryResponse) {

            if (aryResponse.success) {
                var aryData = aryResponse.aryData;
                console.log(aryData);

                $("#formNegocio").find(".modal-title").html('Editar Negocio');
                $("#formNegocio").modal("show");

                $("#sNombre").val(aryData.aryNegocio.sNombre);
                $("#sDireccion").val(aryData.aryNegocio.sDireccion);
                $("#nTipoProspecto").val(aryData.aryNegocio.nTipoProspecto);
                $("#nEstado").val(aryData.aryNegocio.nEstado);
                $("#sImagen").parent().find(".custom-file-label").html(aryData.aryNegocio.sImagen);

                $("#nIdPais").val(aryData.aryNegocio.nIdPais);
                $("#sCiudad").val(aryData.aryNegocio.sCiudad);
                $("#nIdMoneda").val(aryData.aryNegocio.nIdMoneda);
                $("#nPorcentajeTributo").val(aryData.aryNegocio.nPorcentajeTributo);
    
                fncActivarDescbyEntidades(aryData.aryConfigClientes);
                fncActivarDescbyEntidades(aryData.aryConfigCatalogos);
                fncActivarDescbyEntidades(aryData.aryConfigVendedores);
                fncActivarDescbyEntidades(aryData.aryConfigSupervisores);

            } else {
                toastr.error(aryData.error);
            }
        });

    }

    function fncValidateUser() {
        // Si tiene el flag activado de crear negocio el usuario podra crear 
        if ('<?= $user["nCrearNegocio"] ?>' == 1) {
            $("#btnCrearNegocio").show();
        } else {
            $("#btnCrearNegocio").hide();
        }

        $("#btnEditarUsuarioEmpleado").show();
    }



    // Funciones Auxiliares

    function fncDrawNegocios() {
        fncGetNegocios({}, function(aryData) {
            if (aryData.success) {

                var sHtmlTemplate = ``;

                if (aryData.aryData.length > 0) {

                    $.each(aryData.aryData, function(nIndex, aryValue) {

                        var isAdmin = false;
                        var isInvitado = false;

                        // Solo si es usuario va a lidar el flag

                        if (aryValue.nIdRol == 1) {
                            isAdmin = true;
                        }

                        if (aryValue.nIdRol == 2) {
                            isInvitado = true;
                        }

                        sHtmlTemplate += `
                                            <figure class="col-md-4 text-center">
                                                        <div class="position-relative contenedor-negocio text-center">
                                                            <a href="${route('home/' + aryValue.nIdNegocio + '/' + aryValue.nIdRol)}">
                                                                <img alt="picture" src="${src( 'multi/' + aryValue.sImagen )}" class="img-fluid img-mis-negocios">
                                                                <figcaption class="figure-caption">${aryValue.sNombre}</figcaption>
                                                            </a>
                                                            <div class="actions-negocio">
                                                            ${isAdmin ? `<a href="javascript:;" onclick="fncListarUsuarios(${aryValue.nIdNegocio});" title="Listado de usuarios"><i class="material-icons">list_alt</i> </a>` : ``}  
                                                            ${isAdmin ? `<a href="javascript:;" onclick="fncInvitarUsario(${aryValue.nIdNegocio}, ${ '`'+  fncEncodeHTMLValue(`${aryValue.sNombre.trim()}` + '`') });" title="Invitar usuario"><i class="material-icons">person_add</i> </a>` : ``}  
                                                            ${isAdmin ? `<a href="javascript:;" onclick="fncMostrarRegistro(${aryValue.nIdNegocio});" title="Editar"><i class="material-icons">edit</i> </a>` : ``}  
                                                            ${isAdmin ? `<a class="text-danger" href="javascript:;" onclick="fncEliminarRegistro(${aryValue.nIdNegocio});" title="Eliminar"><i class="material-icons">delete</i> </a>` : ( isInvitado ?  ` <a  class="text-danger" href="javascript:;" onclick="fncEliminarInvitacion(${aryValue.nIdNegocio},${aryValue.nIdUsuario});" title="Eliminar Invitacion"><i class="material-icons">delete</i> </a> ` : '')}  
                                                            </div>
                                                        </div>
                                            </figure>
                        `;
                    });
                } else {
                    sHtmlTemplate += `<div class="col-md-12 text-center">No se ubicaron resultados</div>`;
                }
                $("#list-negocios").html(sHtmlTemplate);
            }
        });
    }



    function fncCleanAll() {
        fncClearInputs($("#formNegocio").find("form"));
        fncClearInputs($("#formCliente").find("form"), true);
        fncClearInputs($("#formProductosoServicios").find("form"), true);
        fncClearInputs($("#formVendedores").find("form"), true);
        fncClearInputs($("#formSupervisores").find("form"), true);
    }

    function fncGetAryCampos(sHtmlTag) {
        var ary = [];

        $(sHtmlTag).each(function(nIndex, objCheck) {

            ary.push({
                nIdCampoEntidad: $(objCheck).val(),
                nEstado: $(objCheck).is(':checked') ? 1 : 0,
                nIdConfiguracionCampo: $("#sNombre").data("nIdRegistro") == 0 ? 0 : $(objCheck).data("nIdConfiguracionCampo")
            });

        });

        return ary;
    }

    function fncActDescCheck(sHtmlTagPadre, sHtmlTagHijo) {
        $(sHtmlTagPadre).click(function() {

            if ($(this).is(':checked')) {
                $(sHtmlTagHijo).prop('checked', true);
            } else {
                $(sHtmlTagHijo).prop('checked', false);
            }

        });
    }

    // Esta funcion sirtve cuando se edita y se activa o desactiva los checks
    function fncActivarDescbyEntidades(aryData) {
        $.each(aryData, function(nIndex, aryItem) {

            var sHtmlTag = '#chk' + aryItem.nIdCampoEntidad;

            if (parseInt(aryItem.nEstado) == 1) {
                $(sHtmlTag).prop('checked', true);
            } else {
                $(sHtmlTag).prop('checked', false);
            }

            $(sHtmlTag).data("nIdConfiguracionCampo", aryItem.nIdConfiguracionCampo);

        });
    }

    // Llamadas al servidor

    function fncGrabarNegocio(formData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncGrabarNegocio',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncGetNegocios(jsnData = {}, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncGetNegocios',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncEjecutarEliminarRegistro(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            url: web_root + 'admin/negocios/fncEliminarRegistro',
            data: jsnData,
            dataType: 'json',
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }

        });
    }

    function fncEjecutarEliminarUsuarioNegocio(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            url: web_root + 'admin/negocios/fncEliminarUsuarioNegocio',
            data: jsnData,
            dataType: 'json',
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }

        });
    }


    function fncBuscarRegistro(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncMostrarRegistro',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }
</script>


<!-- Invitar Usuario -->
<script>
    $(function() {



        $("#formInvitarUsuario").find('form').on('submit', function(event) {

            event.preventDefault();

            var nIdNegocio = $("#formInvitarUsuario").data("nIdNegocio");
            var sNombre = $("#formInvitarUsuario").data("sNombre");
            var sCorreoInvitacion = $("#sCorreoInvitacion").val().trim();
            var nRol = $("#nRol").find("option:selected").val();

            if (sCorreoInvitacion == '') {
                toastr.error('Error. Debe ingresar un correo para la invitacion del usuario . Porfavor verifique');
                return;
            }

            var jsnData = {
                nIdNegocio: nIdNegocio,
                sNombre: sNombre,
                sCorreoInvitacion: sCorreoInvitacion,
                nRol: nRol
            };

            fncProcesarInvitacionNegocio(jsnData, function(aryData) {

                if (aryData.success) {

                    $("#formInvitarUsuario").modal("hide");

                    toastr.success(aryData.success);

                } else {

                    toastr.error(aryData.error);

                }

            });


        });


    });

    // Funciones de la tabla o layout Principal 




    // Funciones Auxiliares



    window.fncInvitarUsario = (nIdNegocio, sNombreNegocio) => {

        var jsnData = {
            nIdNegocio: nIdNegocio
        };

        sNombreNegocio = fncDecodeHTMLValue(sNombreNegocio);

        console.log(sNombreNegocio);

        $("#nTipoUsuarioInvitar").val(2).trigger("change");

        $("#formInvitarUsuario").data("nIdNegocio", nIdNegocio);
        $("#formInvitarUsuario").data("sNombre", sNombreNegocio);

        $("#formInvitarUsuario").modal("show");
    }



    // Llamadas al servidor

    function fncGetUsuariosInvitacion(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncGetUsuariosInvitacion',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncProcesarInvitacionNegocio(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncProcesarInvitacionNegocio',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }
</script>
<!-- Invitar Usuario -->


<!-- Listar Usuarios -->
<script>
    window.fncListarUsuarios = function(nIdNegocio) {
        var jsnData = {
            nIdNegocio: nIdNegocio
        };

        fncMostrarUsuariosNegocios(jsnData, (aryData) => {

            if (aryData.success) {

                var aryData = aryData.aryData;

                var sHtml = ``;

                if (aryData.length > 0) {

                    aryData.forEach(aryItem => {
                        sHtml +=
                            `<div class="card my-2 p-2 w-100 mx-4">
                            <div class="d-flex flex-center">
                                <div>${fncUc(aryItem.sUsuario)} - ${aryItem.sRol} </div>
                                <div class="ml-auto"></div>
                                <div class="mx-2"><a href="javascript:;" class="text-danger font-18" onclick="fncEliminarRelacionUsuario(${aryItem.nIdNegocio}, ${aryItem.nIdUsuario});" title="Eliminar"><i class="material-icons">delete</i></a></div>
                            </div>
                        </div>`;
                    });

                } else {
                    sHtml = `<h6> No existen usuarios invitados </h6>`;
                }

                $("#lista-usuarios").html(sHtml);
                $("#formListarUsuarios").modal("show");
            } else {
                toastr.error(aryData.error);
            }
        });

    }

    window.fncEliminarRelacionUsuario = function(nIdNegocio, nIdUsuario) {
        if (confirm('Esta acción eliminará permanentemente la invitacion y no podrá deshacerse. ¿ Esta seguro de continuar ?')) {

            var jsnData = {
                nIdNegocio: nIdNegocio,
                nIdUsuario: nIdUsuario
            };

            fncEjecutarEliminarUsuarioNegocio(jsnData, function(aryData) {

                if (aryData.success) {
                    fncListarUsuarios(nIdNegocio);
                    toastr.success(aryData.success);
                } else {
                    toastr.error(aryData.error);
                }

            });
        }
    }


    // Llamadas al servidor    
    function fncMostrarUsuariosNegocios(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/negocios/fncMostrarUsuariosNegocios',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }
</script>
<!-- Listar Usuarios -->




</html>