<!DOCTYPE html>
<html class="no-js h-100" lang="es">

<head>
    <?php extend_view(['admin/common/head'], $data) ?>
    <?php load_style(['bootstrap', 'jquery-ui', 'admin/style', 'admin/shards-dashboards.1.1.0.min']); ?>
    <?php load_style_plugin(['toast/toastr.min', 'select2/select2', 'select2/select2-bootstrap', 'bootstrap-table/bootstrap-table']); ?>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body data-nidnegocio="<?= $nIdNegocio ?>">


    <div class="page-loader">
        <div class="loader-dual-ring"></div>
    </div>


    <div class="container-fluid">

        <div class="row">

            <?php extend_view(['admin/common/aside'], $data) ?>

            <main class="main-content col-lg-10 col-md-9 col-sm-12 p-0 offset-lg-2 offset-md-3">

                <?php extend_view(['admin/common/navbar'], $data) ?>

                <div class="main-content-container container-fluid px-2 my-2">

                    <div class="container-fluid px-0">
                        <div class="page-header row no-gutters pb-4">


                            <div class="col-lg-12 col-md-12 col-sm-12 mb-4">
                                <div class="card card-small">
                                    <div class="card-body pt-0 pb-5">

                                        <div class="row">
                                            <div class="col-12">
                                                <div class="d-flex ">
                                                    <div class="d-flex align-items-center p-2">
                                                        <span class="title-prospectos">Reporte por Clientes</span>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="row flex-center">
                                            <div class="col-12 col-md-12 my-0">


                                                <div id="toolbarBDClientes">
                                                    <button id="btnFilter" class="btn btn-gradient-primary-table mx-1" type="button" title="Filtros">
                                                        <i class="fas fa-filter"></i>
                                                    </button>
                                                </div>

                                                <div class="table-responsive">

                                                    <table data-toggle="table" id="tblBDClientes" 
                                                    data-export-types="['json', 'xml', 'csv', 'txt', 'pdf', 'excel']" data-export-options='{
                                                            "fileName": "tableExport",
                                                            "ignoreColumn": ["sHistorico"],
                                                            "worksheetName": "tableExport",
                                                            "htmlContent" : "true",
                                                            "jspdf": {
                                                                    "autotable": {
                                                                        "startY": 30,
                                                                        "bodyStyles": {"valign": "top"},
                                                                        "styles": {"overflow": "linebreak", "rowHeight": 30, "fontSize": 6, "font": "helvetica"},
                                                                        "headerStyles": {"fillColor": [41, 128, 185]},
                                                                        "tableWidth": "wrap",
                                                                        "columnStyles" : { "columnWidth" : "auto"  }
                                                                    }
                                                                }
                                                            }' 
                                                            data-show-export="true" 
                                                            data-mobile-responsive="true"
                                                            data-card-view="false" 
                                                             data-search="true" data-query-params="queryParams" toolbarAlign="left" data-show-refresh="false" data-pagination="true" data-toolbar="#toolbarBDClientes" data-buttons-align="left" data-show-columns="true" data-pagination-h-align="left" data-pagination-detail-h-align="right" data-classes="table table-hover table-condensed" data-striped="true" data-buttons-class="gradient-primary-table" data-card-view="false" data-page-size="14" data-sort-name="" data-sort-order="asc">
                                                        <thead>
                                                            <tr>
                                                                <th data-field="sNombreoRazonSocial" data-sortable="true">Nombre</th>
                                                                <th data-field="sNumeroDocumento" data-sortable="true">Documento</th>
                                                                <th data-field="sDireccion" data-sortable="true">Direccion</th>
                                                                <th data-field="sContacto" data-sortable="true">Contacto</th>
                                                                <th data-field="sRelacionamiento" data-sortable="true">Relacionamiento</th>
                                                                <th data-field="sCorreo" data-sortable="true">Correo</th>
                                                                <th data-field="sTelefono" data-sortable="true">Telefono</th>
                                                                <th data-field="sTiempoCreacion" data-sortable="true">Tiempo de creacion</th>
                                                                <th data-field="sHistorico" data-tableexport-display="none" data-sortable="true">Historico</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>

                                                        </tbody>
                                                    </table>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>


                </div>

            </main>
        </div>
    </div>



    <!-- Modales -->


    <?php extend_view(['admin/common/modales-editar'], $data) ?>


    <div class="modal fade" id="formHistorialCliente" tabindex="-1" role="dialog" aria-labelledby="formHistorialClienteLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <form enctype="multipart/form-data">
                    <div class="modal-header">
                        <h5 class="modal-title" id="formHistorialClienteLabel">Historial</h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                    <div class="modal-body modal-body-scroll">

                        <div id="toolbarHistorial"></div>

                        <div class="table-responsive">

                            <table data-toggle="table" id="tblHistorial" data-card-view="false" data-toggle="table" data-search="true" data-query-params="queryParams" toolbarAlign="left" data-show-refresh="false" data-pagination="true" data-toolbar="#toolbarHistorial" data-buttons-align="left" data-show-columns="true" data-pagination-h-align="left" data-pagination-detail-h-align="right" data-classes="table table-hover table-condensed" data-striped="true" data-buttons-class="gradient-primary-table" data-card-view="false" data-page-size="14" data-sort-name="" data-sort-order="asc">
                                <thead>
                                    <tr>
                                        <th data-field="nItem" data-sortable="true">Item</th>
                                        <th data-field="sCliente" data-sortable="true">Cliente</th>
                                        <th data-field="sEmpleado" data-sortable="true">Empleado</th>
                                        <th data-field="sNombreEtapa" data-sortable="true">Etapa</th>
                                        <th data-field="nTotal" data-sortable="true">Total</th>
                                        <th data-field="dFechaCreacion" data-sortable="true">Fec. Creacion</th>
                                        <th data-field="dFechaHoraUltimoAcceso" data-sortable="true">Ult. Edicion</th>
                                    </tr>
                                </thead>
                                <tbody>

                                </tbody>
                            </table>

                        </div>


                    </div>
                    <div class="modal-footer">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="modal fade" id="formFilter" tabindex="-1" role="dialog" aria-labelledby="formFiltersLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form enctype="multipart/form-data">

                    <div class="modal-header">
                        <h5 class="modal-title" id="formFiltersLabel">Filtrar reporte </h5>
                        <button type="button" class="btn btn-close btn-gradient-primary btn-rounded p-0" data-dismiss="modal" aria-label="Close">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>

                    <div class="modal-body">

                        <div class="row">
                            <div class="col-md-12 col-12">
                                <div class="form-group">
                                    <label for="" class="col-form-label">Tipo Cliente:</label>
                                    <select class="form-control" name="nTipoCliente" id="nTipoCliente">
                                        <option value="0">TODOS</option>
                                        <option value="1">EMPRESA</option>
                                        <option value="2">PERSONAS</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-gradient-primary btn-fw btn-submit">Filtrar</button>
                    </div>

                </form>

            </div>
        </div>
    </div>



    <!-- Fin de modales -->

</body>


<?php extend_view(['admin/common/scripts'], $data) ?>

<?php load_script(['jquery', 'jquery-ui', 'popper', 'bootstrap', 'moment', 'admin/custom', 'admin/functions', 'admin/edit-user-empleado', 'admin/app']); ?>
<?php load_script_plugin([
    'toast/toastr.min',
    'select2/select2',

    'bootstrap-table/bootstrap-table',
    'bootstrap-table/bootstrap-table-es-ES',

    'bootstrap-table/export/tableExport/tableExport',
    'bootstrap-table/export/tableExport/html2canvas',
    'bootstrap-table/export/tableExport/jquery.base64',
    'bootstrap-table/export/tableExport/tableExport',
    'bootstrap-table/export/bootstrap-table-export',


    'bootstrap-table/mobile/bootstrap-table-mobile',
    'bootstrap-table/tableExport/libs/FileSaver/FileSaver.min',
    'bootstrap-table/tableExport/libs/js-xlsx/xlsx.core.min',
    'bootstrap-table/tableExport/libs/jsPDF/jspdf.min',
    'bootstrap-table/tableExport/libs/jsPDF-AutoTable/jspdf.plugin.autotable',
    'bootstrap-table/tableExport/libs/pdfmake/pdfmake.min',
    'bootstrap-table/tableExport/libs/pdfmake/vfs_fonts',
    'bootstrap-table/tableExport/tableExport.min',
]); ?>


<!-- BD Clientes -->
<script>
    $(document).ready(function() {

        $("#btnFilter").on("click",function(){
            $("#formFilter").modal("show");
        });


        window.fncVerHistorial = function(nIdCliente) {

            var jsnData = {
                nIdCliente: nIdCliente,
                nIdNegocio: <?= $nIdNegocio ?>
            };

            fncPopulateHistorialCliente(jsnData, (aryData) => {

                if (aryData.success) {
                    $("#tblHistorial").bootstrapTable("load", aryData.aryData);
                    $("#formHistorialCliente").modal("show");
                    toastr.success(aryData.success);
                } else {
                    toastr.error(aryData.error);
                }

            });
        }

        $("#formFilter").find("form").on('submit', function(event   ) {
            event.preventDefault();

            var nTipoCliente = $("#nTipoCliente").val() == '0' ? null : $("#nTipoCliente").val();

            var jsnData = {
                nIdNegocio   : <?= $nIdNegocio ?>,
                nTipoCliente : nTipoCliente
            };

            fncDrawTableBDClientes(jsnData);
        });

        $("#formFilter").find("form").trigger('submit');
    });

    // Funciones Auxiliares



    // // Funciones Auxiliares 

    window.fncDrawTableBDClientes = function(jsnData) {

        fncGetClientesParaAdmin(jsnData, (aryData) => {

            if (aryData.success) {

                $("#tblBDClientes").bootstrapTable("load", aryData.aryData);
                $("#formFilter").modal("hide");

            } else {
                toastr.error(aryData.error);
            }

        });
    }



    // LLamadas al servidor 

    function fncGetClientesParaAdmin(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/cliente/fncGetClientesParaAdmin',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }

    function fncPopulateHistorialCliente(jsnData, fncCallback) {
        $.ajax({
            type: 'post',
            dataType: 'json',
            url: web_root + 'admin/prospecto/fncPopulateHistorialCliente',
            data: jsnData,
            beforeSend: function() {
                fncMostrarLoader();
            },
            success: function(data) {
                fncCallback(data);
            },
            complete: function() {
                fncOcultarLoader();
            }
        });
    }
</script>
<!--  BD Clientes -->



</html>