<div class="main-navbar sticky-top bg-white">
    <!-- Main Navbar -->
    <nav class="navbar align-items-stretch navbar-light flex-md-nowrap p-0">
        <?php if (isset($menu) && $menu === true) : ?>
            <div class="navbar__menu flex-row d-none d-md-block">
                <a id="btn-toogle-desktop" class="nav-link nav-link-icon text-center cursor-pointer color-plomo">
                    <i class="material-icons">reorder</i>
                </a>
            </div>
        <?php endif ?>
        <div class="main-navbar__search w-100 d-none d-md-flex d-lg-flex">
            <div class="d-lg-flex align-items-center">

                <div class="mx-1">
                    <i class="fas fa-chart-line" style="color: rgb(0, 123, 255);"></i>
                 </div>

                <div>
                    <?= isset($titulo) && !empty($titulo) ? $titulo   : NOMBRE_SITIO ?>
                </div>
            </div>
        </div>
        <ul class="navbar-nav border-left flex-row">

            <?php if (isset($showNotificacion) && $showNotificacion && $user["nIdRol"] == 1)  : ?>

                <li class="nav-item border-right dropdown">
                    <a class="nav-link nav-link-icon text-center" href="<?= route('mis-negocios/') ?>" role="button" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Mis Negocios">
                        <div class="nav-link-icon__wrapper">
                            <i class="material-icons">business</i>
                        </div>
                    </a>
                </li>

                <li class="nav-item border-right dropdown notifications">
                    <a class="nav-link nav-link-icon text-center" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Notificaciones">
                        <div class="nav-link-icon__wrapper">
                            <i class="material-icons">&#xE7F4;</i>
                            <span id="count-noti" class="badge badge-pill badge-danger">0</span>
                        </div>
                    </a>
                    <div id="content-noti" class="dropdown-menu dropdown-menu-small" aria-labelledby="dropdownMenuLink" style="max-height: 100vh;overflow-y: scroll;height: auto;">

                    </div>
                </li>

            <?php endif ?>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-nowrap px-3" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle mr-2" src="<?= !empty($user['sImagen']) && file_exists(ROOTPATHRESOURCE . "/images/multi/" . $user['sImagen']) ? src('multi/' . $user["sImagen"]) :  src('app/avatar.jpg') ?>" alt="<?= $user['sNombre'] ?>">
                    <span class="d-none d-md-inline-block"><?= fncCutTextName($user['sNombre']) ?></span>
                </a>
                <div class="dropdown-menu dropdown-menu-small">
                    
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" id="btnEditarUsuarioEmpleado" data-nidnegocio="<?=isset( $user["nIdNegocio"] ) ? $user["nIdNegocio"] : 0 ?>" data-nidrol="<?= isset ($user["nIdRol"]) ? $user["nIdRol"] : 0 ?>" data-nid="<?= $user["nIdUsuario"] ?>"  href="javascript:;">
                        <i class="material-icons">manage_accounts</i> Editar
                    </a>

                    <a class="dropdown-item text-danger" href="<?= route('salir') ?>">
                        <i class="material-icons text-danger">&#xE879;</i> Salir
                    </a>

                </div>
            </li>
        </ul>
        <nav class="nav">
            <?php if (isset($menu) && $menu === true) : ?>
                <a href="#" class="nav-link nav-link-icon toggle-sidebar d-md-inline d-lg-none text-center border-left menu-collap">
                    <i class="material-icons">&#xE5D2;</i>
                </a>
            <?php endif ?>
        </nav>
    </nav>
</div>